### ISSUE TITLE
Issue at task: Create fact with VM template

### ISSUE THREAD

**Issue by jhuynh08** [mbach04/nutanix_vm_provisioner#1]
Hi Matt,

Getting an error when it gets to the task: Create fact with VM template. I'm also using python 3 as when I researched the error some people stated that python 3 removed dict.iteritems

ACTUAL RESULTS

TASK [nutanix_provisioner : Create fact with VM template contents] **************************************************************************************************************************************************************************

fatal: [10.71.30.80]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'iteritems'\n\nThe error appears to be in '/etc/ansible/roles/nutanix_provisioner/tasks/provision_vm.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create fact with VM template contents\n ^ here\n"}

**Comment by twling** [comment]
Hello,

Can you make sure the 'global_debug' variable is set to True, and provide the contents of the 'vm_defs' variable that is output just before the "Create fact with VM template contents" task?

**Comment by jhuynh08** [comment]
Timothy,

Please see below for the output. Thank you!


TASK [nutanix_provisioner : Debug | Print VM definitions] ***********************************************************************************************************************************************************************************
ok: [10.71.30.80] => {
    "vm_defs": [
        {
            "vm_disk_list": [
                {
                    "disk_size_mib": 76294
                }
            ],
            "vm_ip": null,
            "vm_name": null,
            "vm_num_cpu_per_socket": null,
            "vm_num_sockets": null,
            "vm_ram": null
        }
    ]
}

TASK [nutanix_provisioner : Create fact with VM template contents] **************************************************************************************************************************************************************************
fatal: [10.71.30.80]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'iteritems'\n\nThe error appears to be in '/etc/ansible/roles/nutanix_provisioner/tasks/provision_vm.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create fact with VM template contents\n  ^ here\n"}


> Hello,
> 
> Can you make sure the 'global_debug' variable is set to True, and provide the contents of the 'vm_defs' variable that is output just before the "Create fact with VM template contents" task?

**Comment by jhuynh08** [comment]
Tim,

Sorry here is the updated playbook with the contents filled in.

TASK [nutanix_provisioner : Debug | Print VM definitions] ***********************************************************************************************************************************************************************************
ok: [10.71.30.80] => {
    "vm_defs": [
        {
            "vm_disk_list": [
                {
                    "disk_size_mib": 76294
                }
            ],
            "vm_ip": "10.71.30.50",
            "vm_name": "RVLRH01",
            "vm_num_cpu_per_socket": 2,
            "vm_num_sockets": 2,
            "vm_ram": 4092
        }
    ]
}

**Comment by twling** [comment]
Removed the iteritems() for items(), changes pushed to master. Let me know if that works out for you.

**Comment by mbach04** [comment]
I just kicked off the import job on ansible-galaxy again. So if you're pulling this role from galaxy, you'll need to update.

**Comment by jhuynh08** [comment]
Looks like it works now, thanks guys!

Just a quick question on the side: If I want to provision a VM without setting an IP address. Would I just need to leave the vm_ip variable blank in my playbook?

**Comment by twling** [comment]
I'm not sure leaving vm_ip would work. That field in the API call to nutanix is not required, but it is unknown what happens when the field is blank. If you are looking for implementing DHCP, you will want to modify the templates/vm-body.yml.j2 file and replace "- ip: {{ vm.vm_ip }}" with "- ip_type: DHCP"

**Comment by jhuynh08** [comment]
That was what I was exactly looking for. Thank you again!
