### ISSUE TITLE
Issue creating VM without guest customization

### ISSUE THREAD

**Issue by K3ndu** [mbach04/nutanix_vm_provisioner#2]
Hello!

We are trying to use Playbook without the guest customization at first, but are encountering error we cant seem to find a solution.

Playbook:
---
- name: Provision some VMs
  hosts: localhost
  gather_facts: false
  vars:
    my_vms:
      - {vm_name: 'test', vm_ip: '10.0.0.0', vm_ram: 2048, vm_num_cpu_per_socket: 1, vm_num_sockets: 4, vm_disk_list: [disk_size_mib: 10000]}
  tasks:
    - name: Provision VMs on Nutanix
      include_role:
        name: nutanix
      vars:
        vm_defs: "{{ my_vms }}"

Removed the following lines from vm-body.yml.y2:
    guest_customization:
      cloud_init:
        user_data: {{ lookup('template','cloud-init.yml.j2') | b64encode }}

Error is following:
TASK [nutanix : Debug | Print VM definitions] *********************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "vm_defs": [
        {
            "vm_disk_list": [
                {
                    "disk_size_mib": 10000
                }
            ],
            "vm_ip": "10.0.0.0",
            "vm_name": "test",
            "vm_num_cpu_per_socket": 1,
            "vm_num_sockets": 4,
            "vm_ram": 2048
        }
    ]
}

TASK [nutanix : Create fact with VM template contents] ************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ lookup('template', 'vm-body.yml.j2') | from_yaml }}): a string or stream input is required"}

**Comment by mbach04** [comment]
@K3ndu ensure all variables are defined. Additionally, we just merged an update to the jinja template and updated it on ansible-galaxy. Try updating your role and running it again.

**Comment by K3ndu** [comment]
@mbach04 I have all variables defined in main.yml but it's still giving this error even after the update.
I have removed the three lines from vm-body.yml.j2 that are guest_customization part but it seems to me that some part of the code is still looking for it and complains that it cant't find the guest_customization from vm-body.yml.j2. Any ideas?

**Comment by twling** [comment]
I don't think myself or @mbach04 currently have access to a Nutanix cluster to test the API functionality, so troubleshooting this may be a bit difficult. The good news is that I don't think this is an API issue, it's failing before it gets to the POST step.

I'm having trouble reproducing your error. I removed the same 3 lines from the `vm-body.yml.j2` file, and used your same definition for `vm_defs` and the "Create fact with VM template contents" step complete in generating the template.

**Comment by K3ndu** [comment]
No fix needed
