### ISSUE TITLE
Issue creating VM with disks in specific storage container

### ISSUE THREAD

**Issue by Andrew-Callan** [mbach04/nutanix_vm_provisioner#4]
I've tried examining the API for creating a VM from the explorer on my Nutanix cluster, however several of the fields in vm-body.yml.j2 and the official field names in the REST API explorer are different, for example "nic_list" in the j2 file and "vm_nics" on the REST API explorer. I've attempted to include the storage_container_uuid: "string" in the vm-body.yml.j2 file and received the following error. We're trying to place the disks within a container that has compression and EC enabled and would really rather not use the default container with edits made to it's config. Any help would be appreciated, below is the contents of my vm-body.yml/j2 file.

api_version: '3.0'
metadata:
  kind: vm
spec:
  cluster_reference:
    kind: cluster
    uuid: {{ cluster_uuid }}
  name: {{ vm.vm_name }}
  resources:
    disk_list:
    - data_source_reference:
        kind: image
        uuid: {{ image_uuid }}
{% for disk in vm.vm_disk_list %}
{% for k,v in disk.items() %}
    - {{ k }}: {{ v }}
{% endfor %}
{% endfor %}
    memory_size_mib: {{ vm.vm_ram }}
    nic_list:
{% if vm.vm_ip is defined %}
    - ip_endpoint_list:
      - ip: {{ vm.vm_ip }}
{% endif %}
{% if subnet_uuid is defined and vm.vm_ip is defined %}
      subnet_reference:
        kind: subnet
        uuid: {{ subnet_uuid }}
{% elif subnet_uuid is defined and vm.vm_ip is not defined %}
    - subnet_reference:
        kind: subnet
        uuid: {{ subnet_uuid }}
{% endif %}
    num_sockets: {{ vm.vm_num_sockets }}
    num_vcpus_per_socket: {{ vm.vm_num_cpu_per_socket }}
   storage_container_uuid: {{ storage_cont_uuid }}
   power_state: 'ON'
    guest_customization:
      cloud_init:
        user_data: {{ lookup('template','cloud-init.yml.j2') | b64encode }}

**Comment by Andrew-Callan** [comment]
Error shows as:
"Additional properties are not allowed (u'storage_container_uuid' was unexpected)

**Comment by Andrew-Callan** [comment]
Realized I was on different  version of the API. V3 has no support for specifying a container for the attached disks.

**Comment by mbach04** [comment]
@Andrew-Callan Have you found the Nutanix Developer Portal yet? The API's are pretty well spec'd out here: https://www.nutanix.dev/api-reference/.
They're also available in a cluster if you have access to one.

**Comment by Andrew-Callan** [comment]
I've got access to a couple of clusters, looking at the API explorer it seems there's no method of specifying a storage container to use for disks being attached to a VM.

**Comment by mbach04** [comment]
There are some storage parameters available here for an existing VM, but I see nothing referring to a container though: https://www.nutanix.dev/reference/prism_central/v3/api/vms/putvmsuuid

I'd post over in r/Nutanix on Reddit if you need to resolve this. They're pretty responsive with their developer community. Happy to merge in a PR to add features.
