### ISSUE TITLE
Concatenate str

### ISSUE THREAD

**Issue by mdf-ido** [mbach04/nutanix_vm_provisioner#7]
We are getting an error at the Stash the image task. Can you advice what is the purpose of default([])? from our understanding it seems that you are trying to set the variable image_uuids to the result of query: default([]) + [ {'name': item.spec.name, 'uuid': item.metadata.uuid but please correct me if I am wrong. I am trying to see if I can write another query to get the value and define the variable

Error: 
_fatal: [nutanixserver]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ image_uuids | default([]) + [ {'name': item.spec.name, 'uuid': item.metadata.uuid } ] }}): can only concatenate str (not \"list\") to str"}_

- name: Stash the image UUIDs
  set_fact:
    image_uuids: "{{ image_uuids | default([]) + [ {'name': item.spec.name, 'uuid': item.metadata.uuid } ] }}"

**Comment by mbach04** [comment]
By chance, does your Nutanix cluster have images in the data store already?

**Comment by mbach04** [comment]
To verify what's coming down just do a debug task before [Line 26](https://github.com/mbach04/nutanix_vm_provisioner/blob/master/tasks/get_image_uuids.yml#L26) to print out the variable registered as `json_images_result`

**Comment by mdf-ido** [comment]
Thanks for your response! We do have the images in the datastore and I was able to see results from the debug task. I believe the issue is concatenating `default([]) + [ {'name': item.spec.name, 'uuid': item.metadata.uuid } `  

I am also getting values on the task step to stash the image UUIDs

`TASK [nutanix_provisioner : Stash the image UUIDs] ******************************************************************************************************************************************************************************************
ok: [x.x.x.x] => (item={'status': {'state': 'COMPLETE', 'name': 'VirtIO 1.x.x', 'resources': {'retrieval_uri_list': ['https://127.0.0.1:9440/api/nutanix/v3/images//file'], 'image_type': 'ISO_IMAGE', 'source_uri': 'file://###sssddsf-db##-4##3-9###-08a6d###aaa#', 'architecture': 'X86_64', 'size_bytes': 48695296}, 'description': 'VirtIO'}, 'spec': {'name': 'VirtIO 1.x.x', 'resources': {'image_type': 'ISO_IMAGE', 'source_uri': 'file://d####-db##-4###-9###-08##aa##', 'architecture': 'X86_64'}, 'description': 'VirtIO'}, 'metadata': {'kind': 'image', 'spec_version': 0, 'uuid': 'e2####3-626b-###-###-#####6b0a8', 'categories': {}}})`


### Error:

`fatal: [x.x.x.x]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ image_uuids | default([]) + [ {'name': item.spec.name, 'uuid': item.metadata.uuid } ] }}): can only concatenate str (not \"list\") to str"}`

### Questions:
- What should be an expected result from `image_uuids: "{{ image_uuids | default([]) + [ {'name': item.spec.name, 'uuid': item.metadata.uuid } ] }}"` ?
- JSON output showed API 3.1. is this ok?

Thanks for your responses and advice!

**Comment by mdf-ido** [comment]
FYI: I hard coded the image uuid in define_uuids_from_names.yml and got past the error. Looking at the json result to dictionary. It will be great if you have a .py script on this that you can share to see and parse the results.
